version: '3.3'

services:
   dind:
     image: docker:dind
     container_name: jenkins-docker
     volumes:
       - jenkins-docker-certs:/certs/client
       - jenkins-data:/var/jenkins_home
     restart: always
     networks:
       jenkins:
          aliases:
             - docker
     privileged: true
     ports:
       - 2376:2376
     environment:
       DOCKER_TLS_CERTDIR: /certs

   jenkins:
     depends_on:
       - dind
     image: jenkinsci/blueocean
     container_name: jenkins-blueocean
     volumes:
       - jenkins-data:/var/jenkins_home
       - jenkins-docker-certs:/certs/client:ro

     ports:
       - 8080:8080
       - 5000:5000
     restart: always
     environment:
       DOCKER_HOST: tcp://docker:2376
       DOCKER_CERT_PATH: /certs/client
       DOCKER_TLS_VERIFY: 1
     networks:
       jenkins:


networks:
  jenkins:
volumes:
  jenkins-data:
  jenkins-docker-certs:
